export { default as About } from './About'
export { default as Bio } from './Bio'
export { default as SocialMedia } from './SocialMedia'
export { default as Languages } from './Languages'
export { default as Skills } from './Skills'
export { default as Hobby } from './Hobby'
export { default as Education } from './Education'
export { default as Experience } from './Experience'
