export { About } from './About'
export { Contact } from './Contact'
export { EducationGroup } from './EducationGroup'
export { Skills } from './Skills'
export { Languages } from './Languages'
export { Hobby } from './Hobby'
export { ExperienceGroup } from './ExperienceGroup'